## Basic Configuration

baseurl = "https://gfleetwood.netlify.com/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "technologiad"
title = "technologiad"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "technologiad"
intro = ""
description = '"We write to taste life twice, in the moment and in retrospect."'
authorimage = "sunyata.png"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "gfleetwood"
#linkedin = "gfleetwood"
#email = "gfleetwood@protonmail.com"
#hackernews = "<username>"
#kickstarter = "<username>"
#patreon = "<username>"
#youtube = "<username>"

## Extras
#[params.extra]
#copyright = "©2019"
#poweredby = true
#highlightjs = true
#socialmarkup = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "rss"
    identifier = "rss"
    weight = 200
    url = "https://gfleetwood.netlify.app/index.xml"
[[menu.main]]
    name = "projects"
    identifier = "projects"
    weight = 300
    url = "/projects/"
