## Basic Configuration

baseurl = "https://gfleetwood.netlify.com/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "technologiad"
title = "technologiad"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "technologiad"
intro = ""
description = "This is my blog for recording my thoughts and projects"
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "gfleetwood"
linkedin = "gfleetwood"
#twitter = "<username>"
#stackoverflow = "<username>"
#hackernews = "<username>"
#kickstarter = "<username>"
#patreon = "<username>"
#youtube = "<username>"
email = "gfleetwood@protonmail.com"

## Extras
[params.extra]
#copyright = "© 2016. Erlich Bachman. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
highlightjs = true
socialmarkup = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "projects"
    identifier = "projects"
    weight = 300
    url = "/projects/"
