---
title: "Resume"
author: Gordon Fleetwood
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
---

<style>

  .col4 {
    columns: 4 100px;         /* number of columns and width in pixels*/
    -webkit-columns: 4 200px; /* chrome, safari */
    -moz-columns: 4 200px;    /* firefox */
  }
  
  .col3 {
    columns: 3 100px;
    -webkit-columns: 3 100px;
    -moz-columns: 3 100px;
  }
  
.col2 {
    columns: 2 100px;
    -webkit-columns: 2 100px;
    -moz-columns: 2 100px;
  }
  
    #column_container {
    width: 959px;
    margin: 0 auto;
}
</style>

<center>
# Gordon Fleetwood
</center>

<p style="text-align:left;">
[gfleetwood.netlify.com](https://gfleetwood.netlify.com/)
<span style="float:right;">gfleetwood@protonmail.com</span>
</p>

<p style="text-align:left;">
[github.com/gfleetwood](https://github.com/gfleetwood)
<span style="float:right;">New York, NY</span>
</p>

### Professional Experience

<p style="text-align:left;">
**Data Analyst**: New Classrooms
<span style="float:right;">2017 - Present</span>
</p>

- Applied Bayesian Analysis in R to evaluate optimal learning pathways for students
- Built a Machine Learning model in Python to predict the probability of a student learning specific Mathematical skills
- Leveraged SQL to pull data for information requests throughout the company
- Redesigned the ETL pipeline for reporting test results
- Wrote detailed reports for non-technical project stakeholders
- Wrote an internal R package to consolidate various data processing tasks
- Leveraged cloud computing for analyses with large data sets.

<p style="text-align:left;">
**Teacher and Teaching Assistant**: NYC Data Science Academy
<span style="float:right;">2016 - 2017</span>
</p>

- Worked with online bootcamp students (individual and corporate) to understand Data Science.
- Taught Python Machine Learning in person to weekend students using the scikit-learn API

<p style="text-align:left;">
**Adjunct Instructor**: CUNY Queens College
<span style="float:right;">2014 - 2017</span>
</p>

- Taught several Mathematics classes including Algebra for Pre-Calculus, Calculus, and Discrete Mathematics

### Personal Projects

**Personal Data Science Libraries**

Description: One for [Python](https://github.com/gfleetwood/handyman) and one for [R](https://github.com/gfleetwood/sansor).

### Skills

Data Science: Data Visualization, Statistical Analysis, Machine Learning, Distributed Computing, Communicating Results

Programming Languages: R, Python, SQL

Other: Linux, Git

### Education

<p style="text-align:left;">
**NYC Data Science Academy**: Data Science Bootcamp
<span style="float:right;">2015</span>
</p>

<p style="text-align:left;">
**CUNY Queens College**: B.A. in Pure Mathematics
<span style="float:right;">2013 - 2014</span>
</p>

<p style="text-align:left;">
**CUNY Queens College**: M.A. in Applied Mathematics 
<span style="float:right;">2009 - 2012</span>
</p>
